---
- hosts: "{{ tty_fix_hosts }}"
  remote_user: centos
  become: yes
  become_user: root

  vars:
    ansible_ssh_pipelining: no

  tasks:
    - name: disable requiretty in /etc/sudoers
      replace: regexp="^Defaults\s+requiretty$" replace="# Defaults    requiretty" dest="/etc/sudoers"
