---
# Playbook for managing a docker instance in the
# openstack cloud.

- hosts: docker-hosts
  vars:
    ansible_user: centos
  roles:
  - role: storage-volume-initialise
    storage_volume_initialise_device: /dev/vdb
    storage_volume_initialise_mount: /var/lib/docker
  - role: basedeps
  - role: system-monitor-agent
  - role: versioncontrol-utils
  - role: docker
    docker_groupmembers: [centos]
    docker_use_ipv4_nic_mtu: True
  - role: sudoers
  - role: local-accounts
